# Generated by Django 2.2.4 on 2019-08-25 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='persona_id',
        ),
        migrations.AddField(
            model_name='usuario',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_persona', to='personal.Persona'),
        ),
    ]
