# Generated by Django 2.2.4 on 2019-08-18 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoContenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo de Contenido')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripcion del tipo de contenido')),
                ('activo', models.BooleanField(default=True, verbose_name='Estado del tipo de contenido')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_eliminacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MisionVision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('mision', models.TextField(verbose_name='Mision de la Institucion')),
                ('fecha_desde', models.DateField(verbose_name='Fecha desde')),
                ('fecha_hasta', models.DateField(verbose_name='Fecha Hasta')),
                ('activo', models.BooleanField(default=True, verbose_name='Estado de la mision')),
                ('tipo', models.CharField(choices=[('MISION', 'MISION'), ('VISION', 'VISION')], default='MISION', max_length=15, verbose_name='Tipo')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_eliminacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo del contenido')),
                ('descripcion', models.TextField(verbose_name='Descripcion del contenido')),
                ('url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Url del contenido')),
                ('archivo', models.FileField(upload_to='documentos_intranet/%Y/%m/', verbose_name='Archivo del contenido')),
                ('mimetype', models.CharField(max_length=50, verbose_name='Mime Type del Archivo')),
                ('fecha_publicacion', models.DateField(verbose_name='Fecha de publicacion')),
                ('fecha_limite', models.DateField(blank=True, null=True, verbose_name='Fecha limite (corte de la publicacion)')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contenido_tipocontenido', to='documento.TipoContenido')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_eliminacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
