# Generated by Django 2.2.4 on 2019-08-25 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documento', '0003_banner_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnlacesSistemas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('enlace', models.URLField(verbose_name='Url del Sistema')),
                ('logo', models.ImageField(upload_to='logosistemas/', verbose_name='Logo del Sistema')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Sistema')),
                ('tipo', models.CharField(choices=[('INTERNO', 'INTERNO'), ('EXTERNO', 'EXTERNO')], default='INTERNO', max_length=15, verbose_name='Tipo de Enlace')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado del enlace')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_eliminacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
