# Generated by Django 2.2.4 on 2019-08-25 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('calificacion', models.CharField(max_length=50, verbose_name='Calificacion')),
                ('color', models.CharField(max_length=15, verbose_name='Color')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_eliminacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoSolicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(max_length=50, verbose_name='Estado de la Solicitud')),
                ('color', models.CharField(max_length=10, verbose_name='Color del estado')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_eliminacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoSoporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo de Soporte')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion del tipo de soporte')),
                ('icono', models.CharField(max_length=20, verbose_name='Icono del Tipo de soporte')),
                ('sistema', models.CharField(max_length=100, verbose_name='Sistema involucrado')),
                ('sigla_sistema', models.CharField(max_length=20, verbose_name='Sigla del Sistema')),
                ('activo', models.BooleanField(default=True, verbose_name='Estado del Tipo de soporte')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_eliminacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(verbose_name='Fecha y hora de solicitud')),
                ('descripcion_solicitud', models.CharField(max_length=150, verbose_name='Descripcion de la solicitud')),
                ('fecha_solucion', models.DateTimeField(verbose_name='Fecha y hora de solucion')),
                ('descripcion_solucion', models.CharField(max_length=250, verbose_name='Descripcion de la solucion')),
                ('calificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitud_calificacion', to='soporte.Calificacion')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitud_estadosolicitud', to='soporte.EstadoSolicitud')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitud_persona', to='personal.Persona')),
                ('tiposoporte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitud_tiposoporte', to='soporte.TipoSoporte')),
                ('usuario_soporte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitud_usuariosoporte', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
